version: '3.4'

services:
    catalogdb:
        container_name: catalogdb
        restart: always
        volumes:
            - ${WEBAPP_STORAGE_HOME}/site:/data/db
        ports:
            - "27017:27017"
    basketdb:
        container_name: basketdb
        restart: always
        ports:
            - "6379:6379"
    orderdb:
        container_name: orderdb
        image: "mcr.microsoft.com/mssql/server"
        restart: always
        environment:
            SA_PASSWORD: "Password_01"
            ACCEPT_EULA: "Y"        
        ports:
            - "1433:1433"         
    rabbitmq:
        container_name: rabbitmq
        restart: always
        ports:
            - "5672:5672"
            - "15672:15672"
    catalog.api:
        container_name: catalogapi
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "CatalogDatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
        depends_on:
            - catalogdb
        ports:
            - "8000:80"            
        volumes:
            - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
            - ${HOME}/.aspnet/https:/root/.aspnet/https/
    basket.api:
        container_name: basketapi
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "ConnectionStrings:Redis=basketdb:6379"
            - "EventBus:HostName=rabbitmq"
        depends_on:
            - basketdb
            - rabbitmq
        ports:
            - "8001:80"
        volumes:
            - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
            - ${HOME}/.aspnet/https:/root/.aspnet/https/
    order.api:
        container_name: orderapi
        restart: on-failure
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "EventBus:HostName=rabbitmq"
            - "ConnectionStrings:OrderConnection=Server=orderdb;Database=OrderDb; User Id=sa;Password=Password_01;"
        depends_on:
            - orderdb
            - rabbitmq
        ports:
            - "8002:80"
        volumes:
            - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
            - ${HOME}/.aspnet/https:/root/.aspnet/https/
    api.gateway:
        container_name: gatewayapi
        restart: on-failure
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        depends_on:
            - catalog.api
            - basket.api
            - order.api
        ports:
            - "7000:80"
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro    
    eshop.web:
        container_name: eshopweb
        restart: on-failure
        depends_on:
            - catalog.api
            - basket.api
            - order.api
            - api.gateway
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "ApiSettings:BaseAddress=gatewayapi"
        ports:
            - "8003:80"           
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
